resource "aws_iam_policy" "ec2_stdt" {
  name        = "ec2_stdt"
  path        = "/"
  description = "EC2 Policy for Students"
 
 policy = <<EOF
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "VisualEditor0",
            "Effect": "Allow",
            "Action": [
                "ec2:DeleteTags",
                "ec2:CreateTransitGatewayRouteTable",
                "ec2:DescribeInstanceAttribute",
                "ec2:AcceptTransitGatewayPeeringAttachment",
                "ec2:ModifyTransitGateway",
                "ec2:AcceptTransitGatewayVpcAttachment",
                "ec2:DescribeAddressesAttribute",
                "ec2:ReplaceTransitGatewayRoute",
                "ec2:DeleteRouteTable",
                "ec2:ModifySubnetAttribute",
                "ec2:AssociateRouteTable",
                "ec2:StartInstances",
                "ec2:CreateRoute",
                "ec2:AssociateTransitGatewayRouteTable",
                "ec2:DisassociateTransitGatewayRouteTable",
                "ec2:ModifyTransitGatewayVpcAttachment",
                "ec2:DisassociateTransitGatewayPolicyTable",
                "ec2:DeleteTransitGatewayPeeringAttachment",
                "ec2:CreateTags",
                "ec2:CreateRouteTable",
                "ec2:RunInstances",
                "ec2:ModifySecurityGroupRules",
                "ec2:AssignPrivateIpAddresses",
                "ec2:StopInstances",
                "ec2:DisassociateRouteTable",
                "ec2:CreateTransitGatewayPolicyTable",
                "ec2:DeleteTransitGatewayRouteTable",
                "ec2:CreateTransitGatewayVpcAttachment",
                "ec2:CreateVpcEndpoint",
                "ec2:AttachNetworkInterface",
                "ec2:GetTransitGatewayPolicyTableAssociations",
                "ec2:EnableTransitGatewayRouteTablePropagation",
                "ec2:CreateNetworkAclEntry",
                "ec2:ModifyVpcEndpoint"
            ],
            "Resource": [
                "arn:aws:ec2:*:642171440217:subnet/*",
                "arn:aws:ec2:*:642171440217:local-gateway-route-table/*",
                "arn:aws:ec2:*:642171440217:transit-gateway-attachment/*",
                "arn:aws:ec2:*:642171440217:transit-gateway-route-table/*",
                "arn:aws:ec2:*:642171440217:natgateway/*",
                "arn:aws:ec2:*:642171440217:transit-gateway/*",
                "arn:aws:ec2:*:642171440217:network-interface/*",
                "arn:aws:ec2:*:642171440217:vpc-endpoint/*",
                "arn:aws:ec2:*:642171440217:transit-gateway-connect-peer/*",
                "arn:aws:ec2:*:642171440217:network-acl/*",
                "arn:aws:ec2:*:642171440217:transit-gateway-policy-table/*",
                "arn:aws:ec2:*:642171440217:instance/*",
                "arn:aws:ec2:*:642171440217:vpc-peering-connection/*",
                "arn:aws:ec2:*:642171440217:local-gateway-route-table-vpc-association/*",
                "arn:aws:ec2:*:642171440217:volume/*",
                "arn:aws:ec2:*:642171440217:security-group/*",
                "arn:aws:ec2:*:642171440217:route-table/*",
                "arn:aws:ec2:*:642171440217:fleet/*",
                "arn:aws:ec2:*:642171440217:dedicated-host/*",
                "arn:aws:ec2:*:642171440217:elastic-ip/*",
                "arn:aws:ec2:*::image/*",
                "arn:aws:ec2:*:642171440217:vpc/*"
            ]
        },
        {
            "Sid": "VisualEditor1",
            "Effect": "Allow",
            "Action": [
                "ec2:DescribeTransitGatewayPolicyTables",
                "ec2:DescribeTransitGatewayPeeringAttachments",
                "ec2:DescribeAddresses",
                "ec2:DescribeInstances",
                "ec2:DescribeRegions",
                "ec2:DescribeTransitGatewayRouteTableAnnouncements",
                "ec2:DescribeTransitGateways",
                "ec2:DescribeTransitGatewayConnectPeers",
                "ec2:DescribeInternetGateways",
                "ec2:DescribeNetworkInterfaces",
                "ec2:DescribeTransitGatewayRouteTables",
                "ec2:DescribeAvailabilityZones",
                "ec2:DescribeNetworkInterfaceAttribute",
                "ec2:DescribeLocalGatewayRouteTableVpcAssociations",
                "ec2:DescribeAccountAttributes",
                "ec2:DescribeLocalGatewayRouteTables",
                "ec2:DescribeNetworkInterfacePermissions",
                "ec2:DescribeVpcEndpointConnections",
                "ec2:DescribeKeyPairs",
                "ec2:DescribeNetworkAcls",
                "ec2:DescribeRouteTables",
                "ec2:GetTransitGatewayRouteTableAssociations",
                "ec2:DescribeLocalGatewayRouteTablePermissions",
                "ec2:DescribeLaunchTemplates",
                "ec2:DescribeTags",
                "ec2:DescribeVpcPeeringConnections",
                "ec2:GetTransitGatewayAttachmentPropagations",
                "ec2:DescribeVpcEndpointServiceConfigurations",
                "ec2:DescribeNatGateways",
                "ec2:DescribeTransitGatewayConnects",
                "ec2:DescribeLocalGateways",
                "ec2:DescribeVpcEndpointConnectionNotifications",
                "ec2:DescribeSecurityGroups",
                "ec2:DescribeLocalGatewayRouteTableVirtualInterfaceGroupAssociations",
                "ec2:DescribeTransitGatewayAttachments",
                "ec2:DescribeSecurityGroupRules",
                "ec2:DescribeSecurityGroupReferences",
                "ec2:DescribeVpcs",
                "ec2:GetTransitGatewayRouteTablePropagations",
                "ec2:DescribePublicIpv4Pools",
                "ec2:DescribeInstanceTypes",
                "ec2:DescribeFleets",
                "ec2:DescribeVpcEndpoints",
                "ec2:DescribeTransitGatewayVpcAttachments",
                "ec2:DescribeSubnets"
            ],
            "Resource": "*"
        }
    ]
}
EOF
}